# Generated by Django 4.1 on 2022-12-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jadwal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jadwal',
            name='accepted',
        ),
        migrations.AlterField(
            model_name='jadwal',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
